name:                haskell-boilerplate
version:             0.1.0.0
github:              "githubuser/haskell-boilerplate"
license:             BSD3
author:              "Cameron Perera"
maintainer:          "cameron.perera@samaritanministries.org"
copyright:           "2018 Cameron Perera"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-boilerplate#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  # Change name of executalbes to your project name
  boilerplate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # This needs to be the same name of the top level directory
    - haskell-boilerplate
    - random

tests:
  # Change name of executalbes to your project name
  boilerplate-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # This needs to be the same name of the top level directory
    - haskell-boilerplate
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-hspec
    - tasty-quickcheck
    - random
